### PR TITLE
feat: added telemetry_int to subscribed napps (same as PR 17)

### LINKED ISSUE #14: Include `telemetry_int` NApp
Eventually, `telemetry_int` NApp should be supported too as specified in the blueprint, and be included on settings.py `DEFAULT_PIPELINE` and `SUBSCRIBED_NAPPS`. 

On `telemetry_int` NApp, the events subscriptions on https://github.com/kytos-ng/telemetry/issues/13  will be prioritized after other PRs land to minimize conflicts, we'll see if it's still doable for version `2023.1` or not. Depending how things evolve we'll set the label `2023.1` later on.

cc'ing @Alopalao for his information.

### PR DESCRIPTION
**Pull request by viniarck**
Closes #14 

### Summary

- Added `telemetry_int` NApp to subscribed napps
- This is @Alopalao's [PR 17](https://github.com/kytos-ng/of_multi_table/pull/17), I had to open a new once since I had to revert 9daba69999037b4f4a625c36f94b71f87c2dde7b
- This change will only land after `2023.1` as discussed on PR 17, so I'll leave this as a draft. 

### Local Tests

Not yet

### CODE REVIEW

**Review by Alopalao — APPROVED** [review]

**Comment by viniarck** [comment]
I've pushed new commits, updating the default pipeline and telemetry_int table groups evpl and epl using [table 2 and 3 respectively](https://github.com/kytos-ng/kytos/blob/master/docs/blueprints/EP031.rst). I've also tested it locally, I'll link the results in other PR and link here too. 

@Alopalao if you could re-review this PR, thanks.

**Comment by viniarck** [comment]
> I've pushed new commits, updating the default pipeline and telemetry_int table groups evpl and epl using [table 2 and 3 respectively](https://github.com/kytos-ng/kytos/blob/master/docs/blueprints/EP031.rst). I've also tested it locally, I'll link the results in other PR and link here too.
> 
> @Alopalao if you could re-review this PR, thanks.

Here's [the related PR](https://github.com/kytos-ng/telemetry_int/pull/64) with more information.

**Review by Alopalao — APPROVED** [review]
Great to see this napp added to multi_table, just a reminder that `telemetry_int` needs to respond to `of_multi_table.enable_table` so `default_pipeline` can be applied correctly. I see that you covered the response in `telemetry_int` [PR](https://github.com/kytos-ng/telemetry_int/pull/64).

**Comment by viniarck** [comment]
> Great to see this napp added to multi_table, just a reminder that `telemetry_int` needs to respond to `of_multi_table.enable_table` so `default_pipeline` can be applied correctly. I see that you covered the response in `telemetry_int` [PR](https://github.com/kytos-ng/telemetry_int/pull/64).

Right. Thanks for your review, Aldo. 

It's great how it's relatively easy is to add new NApps and table groups on `of_multi_table`. 

Let's ship this.

**Comment by viniarck** [comment]
> > Great to see this napp added to multi_table, just a reminder that `telemetry_int` needs to respond to `of_multi_table.enable_table` so `default_pipeline` can be applied correctly. I see that you covered the response in `telemetry_int` [PR](https://github.com/kytos-ng/telemetry_int/pull/64).
> 
> Right. Thanks for your review, Aldo.
> 
> It's great how it's relatively easy is to add new NApps and table groups on `of_multi_table`.
> 
> Let's ship this.

Before shipping it, I also need to address this one here https://github.com/kytos-ng/kytos-end-to-end-tests/issues/263

**Pull request merged**
